import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import './globals.css'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Create Next App',
    description: 'Generated by create next app',
    }

    export default function RootLayout({
      children,
      }: {
        children: React.ReactNode
        }) {
          return (
              <html lang="en">
                    <body className={GeistSans.className}>
                            {children}
                                    <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
                                          </body>
                                              </html>
                                                )
                                                }