'use client'; // This directive is necessary for using hooks like useState and useEffect

import { useEffect, useState } from 'react';
import { auth, db } from './firebase'; // Make sure firebase.js (or .ts) is in the 'app' directory
import { signInAnonymously, onAuthStateChanged, User as FirebaseUser } from "firebase/auth";
import { doc, setDoc, getDoc, serverTimestamp } from "firebase/firestore";

// Define a type for the Telegram user data for better type-checking
interface TelegramUser {
    id: number;
        first_name: string;
            last_name?: string;
                username?: string;
                }

                export default function HomePage() {
                  const [tgUser, setTgUser] = useState<TelegramUser | null>(null);
                    const [firebaseUser, setFirebaseUser] = useState<FirebaseUser | null>(null);
                      const [loading, setLoading] = useState(true);
                        const [error, setError] = useState('');

                          useEffect(() => {
                              // This effect runs once when the component mounts
                                  
                                      // 1. Authenticate with Firebase Anonymously
                                          const unsubscribeAuth = onAuthStateChanged(auth, (user) => {
                                                if (user) {
                                                        setFirebaseUser(user);
                                                              } else {
                                                                      signInAnonymously(auth).catch((err) => {
                                                                                console.error("Firebase anonymous sign-in error:", err);
                                                                                          setError("Could not connect to authentication service.");
                                                                                                  });
                                                                                                        }
                                                                                                            });

                                                                                                                // 2. Initialize Telegram Web App and get user data
                                                                                                                    if (typeof window !== 'undefined' && window.Telegram && window.Telegram.WebApp) {
                                                                                                                          const telegramApp = window.Telegram.WebApp;
                                                                                                                                telegramApp.ready();
                                                                                                                                      
                                                                                                                                            const user = telegramApp.initDataUnsafe?.user;
                                                                                                                                                  
                                                                                                                                                        if (user && user.id) {
                                                                                                                                                                setTgUser(user);
                                                                                                                                                                      } else {
                                                                                                                                                                              setError("Could not retrieve Telegram user data. Please access this app through Telegram.");
                                                                                                                                                                                      setLoading(false);
                                                                                                                                                                                            }
                                                                                                                                                                                                } else {
                                                                                                                                                                                                      // Provide dummy data for development outside of Telegram
                                                                                                                                                                                                            console.warn("Telegram Web App script not found. Using dummy data for development.");
                                                                                                                                                                                                                  setTgUser({ id: 12345678, first_name: "Dev", last_name: "User", username: "devuser" });
                                                                                                                                                                                                                      }

                                                                                                                                                                                                                          return () => {
                                                                                                                                                                                                                                unsubscribeAuth(); // Clean up the auth listener
                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                      }, []);

                                                                                                                                                                                                                                        useEffect(() => {
                                                                                                                                                                                                                                            // This effect runs whenever tgUser or firebaseUser changes
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    // 3. Save user data to Firestore if we have both user objects
                                                                                                                                                                                                                                                        const saveUserDataToFirestore = async () => {
                                                                                                                                                                                                                                                              if (tgUser && firebaseUser) {
                                                                                                                                                                                                                                                                      const userDocRef = doc(db, "users", String(tgUser.id));
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                const docSnap = await getDoc(userDocRef);
                                                                                                                                                                                                                                                                                                          if (!docSnap.exists()) {
                                                                                                                                                                                                                                                                                                                      // User is new, create a new document in Firestore
                                                                                                                                                                                                                                                                                                                                  await setDoc(userDocRef, {
                                                                                                                                                                                                                                                                                                                                                first_name: tgUser.first_name,
                                                                                                                                                                                                                                                                                                                                                              last_name: tgUser.last_name || null,
                                                                                                                                                                                                                                                                                                                                                                            username: tgUser.username || null,
                                                                                                                                                                                                                                                                                                                                                                                          createdAt: serverTimestamp(), // Use server timestamp for consistency
                                                                                                                                                                                                                                                                                                                                                                                                        firebaseUid: firebaseUser.uid,
                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                console.log("New user created in Firestore:", tgUser.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      // User already exists
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log("User already exists in Firestore:", tgUser.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error("Error interacting with Firestore:", err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setError("There was a problem saving your data.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setLoading(false); // Stop loading once the process is complete
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (tgUser && firebaseUser) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        saveUserDataToFirestore();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }, [tgUser, firebaseUser]);


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // --- Render UI based on state ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (loading) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return <div className="flex items-center justify-center min-h-screen">Loading...</div>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return <div className="flex items-center justify-center min-h-screen text-red-500">{error}</div>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <main className="flex flex-col items-center justify-center min-h-screen p-4 bg-gray-900 text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h1 className="text-4xl font-bold mb-2">Welcome Back!</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-2xl text-gray-300">{tgUser?.first_name} {tgUser?.last_name || ''}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-4 text-sm text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>Telegram ID: {tgUser?.id}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Firebase UID: {firebaseUser?.uid}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }